# Generated by Django 6.1 on 2026-08-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='blockchain_block_number',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='blockchain_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, editable=False, max_length=66),
        ),
    ]
